export const roadmapItems = [
  {name: "Reviewer annotations", description: "Highlight manuscript text, write durable editorial comments, accept or dismiss machine findings, set priority, and carry reviewed decisions into author-facing reports.", tags: ["Reviewer", "Editing", "Reports"], ease: 5, impact: 5},
  {name: "Evidence-anchored editorial first pass", description: "Let Qwen propose a small, selective set of passage-anchored editorial notes from chapter text and saved analysis. Proposals remain machine-authored and cannot satisfy sign-off or enter author-facing reports until a human accepts them. Add a disabled-by-default, visibly stamped demo/test override for simulated acceptance without impersonating a real reviewer.", tags: ["Reviewer", "LLM", "Annotations"], ease: 4, impact: 5},
  {name: "Sharper summary and dossier questions", description: "Focus Qwen on specific motivation, causality, character knowledge, relationship change, thematic consequence, reader expectation, and setup/payoff questions instead of generic discussion prompts.", tags: ["Questions", "Prompts", "LLM"], ease: 5, impact: 4},
  {name: "Author action panel", description: "Turn accepted smells, findings, and comments into a rapid chapter-by-chapter editing queue where authors can revise text, respond, defer, or mark an issue resolved.", tags: ["Author", "Editing", "Workflow"], ease: 4, impact: 5},
  {name: "Revision comparison", description: "Compare manuscript versions at line, passage, scene, and chapter scale, then summarize what materially changed and which prior findings became stale or resolved.", tags: ["Versions", "Editing", "Infrastructure"], ease: 4, impact: 5},
  {name: "Portable mini-site", description: "Export a private, model-free analysis site with reviewed findings, plots, annotations, evidence excerpts, and provenance for authors on ordinary computers.", tags: ["Sharing", "Reports", "Author"], ease: 4, impact: 5},
  {name: "Editorial assessment room", description: "Assess clarity, propulsion, character appeal, agency, stakes, payoff, voice, genre fit, and commercial positioning with evidence, counterarguments, and visible model disagreement.", tags: ["Assessment", "LLM", "Reviewer"], ease: 4, impact: 5},
  {name: "Scene purpose map", description: "Identify who wants what, what obstructs them, what changes, and why the next scene follows; surface scenes with weak state change or repeated structural jobs.", tags: ["Structure", "Scenes", "Plot"], ease: 4, impact: 5},
  {name: "Open questions and payoffs", description: "Follow mysteries, promises, setup, repetition, answers, and intentional ambiguity across the manuscript with exact evidence at both endpoints.", tags: ["Continuity", "Reader", "Plot"], ease: 5, impact: 4},
  {name: "Character state ledger", description: "Show where each character begins and ends a chapter: location, goals, knowledge, beliefs, relationships, injuries, possessions, and unresolved intentions.", tags: ["Characters", "Continuity", "Author"], ease: 4, impact: 5},
  {name: "Character intelligence", description: "Combine presence, agency, emotional movement, relationship changes, dialogue share, voice, goals, and causal influence into an evidence-linked portrait of every major character.", tags: ["Characters", "Connections", "Reports"], ease: 4, impact: 5},
  {name: "Causality and coherence map", description: "Distinguish happened-before from caused, enabled, prevented, and motivated; find missing bridges, unsupported decisions, overloaded coincidences, and local non-sequiturs.", tags: ["Causality", "Integrity", "Plot"], ease: 3, impact: 5},
  {name: "Multiple plot arcs", description: "Chart external action, goal progress, agency, emotional pressure, mystery pressure, relationships, revelations, losses, and setup/payoff activity without forcing one universal story curve.", tags: ["Plot", "Charts", "Structure"], ease: 3, impact: 5},
  {name: "Reader memory simulation", description: "Read chapter by chapter as readers with different attention and recall, tracking what feels salient, forgotten, confusing, expected, or genuinely surprising.", tags: ["Reader", "LLM", "Research"], ease: 3, impact: 5},
  {name: "Revision impact graph", description: "After an edit, identify moved anchors, changed obligations, invalidated analyses, newly broken connections, and downstream work that can safely remain cached.", tags: ["Versions", "Infrastructure", "Continuity"], ease: 3, impact: 5},
  {name: "Continuity engine", description: "Reconcile character state, world rules, deadlines, objects, relationships, and reader knowledge to find impossible or unexplained changes across distant chapters.", tags: ["Continuity", "Integrity", "Characters"], ease: 3, impact: 5},
  {name: "Author-intent contracts", description: "Let an author state goals such as ‘keep this a surprise until Chapter 12,’ then test revisions against those intentions as evidence-linked manuscript unit tests.", tags: ["Author", "Intent", "Editing"], ease: 3, impact: 5},
  {name: "Evidence and anchor foundation", description: "Give every observation, comment, event, relationship, and obligation stable source ranges, version signatures, provenance, and repairable anchors across manuscript revisions.", tags: ["Infrastructure", "Provenance", "Versions"], ease: 4, impact: 4},
  {name: "Editorial packet builder", description: "Package reviewed findings, annotations, summaries, charts, evidence, sign-off, and freshness into configurable author, editor-detail, and compact PDF reports.", tags: ["Reports", "Reviewer", "Sharing"], ease: 4, impact: 4},
  {name: "Geography and journey maps", description: "Plot real-world travel or place story events on an author-supplied fictional map, preserving authored order, uncertainty, simultaneous branches, and evidence.", tags: ["Geography", "Charts", "World"], ease: 3, impact: 4},
  {name: "Story chronology graph", description: "Separate narrated order from story time using before/after constraints, durations, dates, ages, flashbacks, simultaneity, uncertainty, and competing placements.", tags: ["Time", "Continuity", "Graph"], ease: 2, impact: 5},
  {name: "Dialogue dynamics", description: "Inspect interruption, dominance, unanswered questions, information asymmetry, subtext, and who changes the direction of a conversation.", tags: ["Dialogue", "Characters", "Scenes"], ease: 3, impact: 4},
  {name: "Semantic Echoes", description: "Use small local embeddings to retrieve callbacks, recurring images, parallel scenes, repeated exposition, and near-duplicate phrasing across distant chapters; let Qwen or an editor explain whether each echo is meaningful, accidental, or excessive.", tags: ["Style", "Retrieval", "Annotations"], ease: 4, impact: 4},
  {name: "Figurative-language density", description: "Map metaphor-related language first with token-level evidence, then add separately evaluated simile, personification, metonymy, hyperbole, symbolism, irony, and imagery layers before claiming an overall figurative density.", tags: ["Style", "Annotations", "Charts"], ease: 3, impact: 4},
  {name: "Entity Signals", description: "Run a fast GLiNER pass that preserves source-anchored mentions of people, places, groups, creatures, artifacts, institutions, events, and speculative entities. Show the lists immediately, then use them to focus dossiers, connections, continuity work, questions, and Qwen review.", tags: ["Entities", "Models", "Infrastructure"], ease: 4, impact: 5},
  {name: "Editorial attention router", description: "Batch a small Jev-compatible decision model before Qwen to rank likely evidence for Smells, Tags, LLM Review, questions, and dossiers. Persist every score and uncertainty, unload the router before Qwen runs, and suppress nothing until held-out human review proves high recall.", tags: ["Models", "Performance", "Infrastructure"], ease: 3, impact: 5},
  {name: "Motif evolution", description: "Trace returning objects, phrases, sensory images, jokes, and symbols—including where an embedding-retrieved echo changes meaning rather than merely recurring.", tags: ["Style", "Themes", "Reader"], ease: 3, impact: 4},
  {name: "Attention budget", description: "Measure how many new names, locations, rules, mysteries, and concepts a reader must absorb at once and where old threads go cold.", tags: ["Reader", "Readability", "Structure"], ease: 3, impact: 4},
  {name: "Editorial calibration corpus", description: "Learn privately from accepted, dismissed, restored, and resolved findings to evaluate detectors and tune ranking to an editor without inventing universal rules.", tags: ["Evaluation", "Reviewer", "Infrastructure"], ease: 2, impact: 5},
  {name: "Editorial sandbox", description: "Move or remove scenes, compare alternate endings, and estimate which promises, knowledge boundaries, causal links, and downstream passages each experiment disturbs.", tags: ["Editing", "Simulation", "Versions"], ease: 2, impact: 5},
  {name: "Time-travel consistency", description: "Extend chronology into branches, loops, overwritten histories, observer-specific knowledge, causal origin, paradox candidates, and uncertain timeline joins.", tags: ["Time", "Science fiction", "Graph"], ease: 1, impact: 5},
  {name: "Character voice test", description: "Hide dialogue attribution and test whether speakers remain distinguishable through vocabulary, rhythm, syntax, interiority, and recurring verbal habits.", tags: ["Dialogue", "Characters", "Style"], ease: 3, impact: 3},
  {name: "Audiobook lens", description: "Find confusable character names, unclear dialogue attribution, typography-dependent meaning, and passages likely to become harder when heard instead of seen.", tags: ["Audio", "Accessibility", "Names"], ease: 3, impact: 3},
  {name: "World-rule ledger", description: "Collect every stated rule, exception, demonstration, and apparent violation for magic systems, technologies, institutions, and fictional cultures.", tags: ["World", "Continuity", "Genre"], ease: 2, impact: 4},
  {name: "Counter-critic panels", description: "For consequential assessments, show the criticism, the strongest evidence-based defense, and an optional judge without silently erasing human judgment.", tags: ["Reviewer", "LLM", "Trust"], ease: 3, impact: 3},
  {name: "Adaptation lens", description: "Expose cast load, location load, effects-heavy sequences, contained episodes, and scene dependencies for adaptation exploration without judging the novel by production cost.", tags: ["Adaptation", "Structure", "Reports"], ease: 2, impact: 3},
  {name: "Book-title collision research", description: "Search exact and similar published titles, explain the kind of overlap, and—where defensible—show sourced, time-stamped market proxies without inventing sales figures.", tags: ["Titles", "Research", "Market"], ease: 2, impact: 2},
];

roadmapItems.forEach((item) => { item.payoff = item.ease * item.impact; });

export const articlePages = {
  about: {
    kicker: "About Bookinator",
    title: "The book is larger than a prompt",
    intro: "Bookinator gives editors a durable, inspectable memory for the whole manuscript—then helps them follow what changes, what connects, and what never quite pays off.",
    tabs: {
      premise: ["The premise", `<section class="information-lede"><p>Find what the author forgot.</p><h2>A novel makes promises across hundreds of pages.</h2><p>A rule appears early. A question is raised and retold. A character knows something they should not. The difficult editorial work is not spotting any one detail—it is remembering the detail when the book finally returns to it.</p></section><section class="principle-ledger"><article><h3>Remember</h3><p>Keep chapter evidence, facts, events, entities, questions, and timeline observations alive beyond the prompt that found them.</p></article><article><h3>Connect</h3><p>Bring distant chapters together so an editor can inspect recurrence, absence, contradiction, setup, and payoff.</p></article><article><h3>Show the evidence</h3><p>Return to the manuscript passage, model run, and saved artifact behind a conclusion instead of accepting a mysterious score.</p></article></section>`],
      work: ["What it does", `<section class="information-lede compact"><p>One book, several lenses</p><h2>Read linearly. Examine structurally.</h2><p>Bookinator turns a manuscript into a navigable editorial workspace without pretending that every observation is equally important.</p></section><div class="capability-bands"><article><strong>Build the memory</strong><h3>Summaries and dossiers</h3><p>Chapter-level reading records what happened and what remains active; whole-book rollups reconcile those records into a larger view.</p></article><article><strong>Map the signals</strong><h3>Emotions, tags, and Smells</h3><p>Chapter-scale analysis exposes story shape and sentences worth an editor’s attention.</p></article><article><strong>Follow the book</strong><h3>Connections and questions</h3><p>Indexes and inference jobs reveal who appears where, what intersects, and where a narrative question receives an answer.</p></article><article><strong>Share the result</strong><h3>Reports and portable exports</h3><p>Professional outputs collect the strongest available analysis without including the source manuscript.</p></article></div>`],
      trust: ["Trust and limits", `<section class="information-lede compact"><p>Editorial aid, not authority</p><h2>The useful answer is inspectable—and disputable.</h2><p>Bookinator produces leads and arguments. A finding can be wrong, overly literal, or blind to deliberate ambiguity. The editor remains responsible for deciding what matters.</p></section><dl class="trust-ledger"><div><dt>Local by design</dt><dd>Manuscripts, derived text, and analysis stay on the editor’s computer. Local models read through Ollama.</dd></div><div><dt>Visible provenance</dt><dd>Saved runs expose status, timing, model identity, failures, source ranges, and available evidence.</dd></div><div><dt>Durable human judgment</dt><dd>Editorial decisions should survive reruns and revisions instead of being overwritten by a fresh model response.</dd></div><div><dt>Honest incompleteness</dt><dd>Missing warnings do not prove a manuscript is sound, and a completed pipeline is not the same thing as a completed edit.</dd></div></dl>`],
    },
  },
  guide: {
    kicker: "Bookinator guide", title: "From manuscript to editorial map", intro: "A practical route through setup, analysis, exploration, and sharing—with the long local jobs made explicit.",
    tabs: {
      start: ["First run", `<section class="information-lede compact"><p>Before the book reads itself</p><h2>Prepare the machine, then verify the manuscript.</h2><p>Analysis is only useful when the local model is ready and the chapter map matches the book you intended to import.</p></section><ol class="guide-path"><li><div><strong>Open Machine</strong><p>Check Python dependencies, Ollama, installed models, and the model assignments Bookinator will use.</p></div></li><li><div><strong>Add a book</strong><p>Import PDF, DOCX, EPUB, TXT, or Markdown. Confirm the title and author before saving it to the local library.</p></div></li><li><div><strong>Inspect Chapters</strong><p>Review the proposed chapter boundaries, including suspicious headings, before committing hours of model work to the wrong structure.</p></div></li><li><div><strong>Choose the analysis</strong><p>Run the chapter and whole-book passes you need. Completed work is saved incrementally.</p></div></li></ol>`],
      workspace: ["The workspace", `<section class="information-lede compact"><p>The book has an operating surface</p><h2>Use Analysis to make evidence. Use Explore to understand it.</h2></section><div class="workspace-guide"><article><span>Identity</span><h3>The book and its source</h3><p>Edit title and author, inspect the ingested manuscript, and keep the object being analyzed unambiguous.</p></article><article><span>Analysis</span><h3>Inspectable production work</h3><p>Pipeline, Chapters, Summaries, Dossiers, Emotions, Tags, Smells, and Inferences show what is ready, running, waiting, or failed.</p></article><article><span>Explore</span><h3>Editorial views and reports</h3><p>Open the summary, emotion map, questions, connections, plot work, retained Smells, and shareable outputs.</p></article><article><span>Reviewer</span><h3>The emerging human layer</h3><p>This is where durable annotations and editorial decisions will increasingly turn analysis into criticism and action.</p></article></div>`],
      jobs: ["Long-running jobs", `<section class="information-lede compact"><p>Local reading takes time</p><h2>The status is part of the result.</h2><p>Large models and long chapters can take minutes apiece. Bookinator keeps the queue visible so waiting never has to mean guessing.</p></section><dl class="status-guide"><div><dt>Waiting</dt><dd>The work is eligible but another saved job is ahead of it.</dd></div><div><dt>Running</dt><dd>The local server has an active attempt. Select the status to inspect model, start time, duration, and input size.</dd></div><div><dt>Complete</dt><dd>A usable artifact was saved. Whole-book work may still be waiting for every required child artifact.</dd></div><div><dt>Failed</dt><dd>The attempt ended without a usable result. Inspect the failure itself, then retry only the affected work.</dd></div></dl><p class="guide-note"><strong>Keep the server terminal open.</strong> Bookinator saves completed work, but the local server and Ollama must remain available while a model is reading.</p>`],
      share: ["Share", `<section class="information-lede compact"><p>After the analysis</p><h2>Export the useful view, not the manuscript.</h2><p>Explore contains polished reports for individual lenses and a larger Share view for the book as a whole.</p></section><div class="share-guide"><article><h3>PDF</h3><p>A branded editorial document with book identity, table of contents, available analysis, and clear disclosure when work is incomplete.</p></article><article><h3>Interactive HTML</h3><p>A model-free, offline report that another person can open on an ordinary computer. It contains selected analysis and provenance, not chapter source text.</p></article></div>`],
    },
  },
  docs: {
    kicker: "Bookinator documentation", title: "How the local system works", intro: "The technical map: browser control surface, loopback server, saved book artifacts, local models, and the boundaries between analysis and reporting.",
    tabs: {
      architecture: ["Architecture", `<section class="information-lede compact"><p>Local application architecture</p><h2>The browser directs; the server owns the work.</h2><p>Bookinator is served on the loopback interface. Its browser UI controls a Python server that owns project files, ingestion, queue state, dependency checks, exports, and communication with Ollama.</p></section><div class="architecture-flow" aria-label="Bookinator architecture"><article><strong>Browser</strong><span>Control surface and inspection</span></article><i aria-hidden="true"></i><article><strong>Bookinator server</strong><span>Files, jobs, state, exports</span></article><i aria-hidden="true"></i><article><strong>Local tools</strong><span>Extraction, detectors, Ollama</span></article></div><p>The application does not need an account or a cloud manuscript upload. Keep the server running while using the UI; stop it with <code>Ctrl-C</code>.</p>`],
      projects: ["Book projects", `<section class="information-lede compact"><p>Durable local state</p><h2>A book is more than its latest model response.</h2><p>Each imported manuscript becomes a local project under <code>.bookinator/</code>. The source and the evidence derived from it remain distinct.</p></section><dl class="artifact-ledger"><div><dt>Source</dt><dd>The imported file and locally extracted text with page provenance.</dd></div><div><dt>Structure</dt><dd>The proposed and accepted chapter map, including source spans and section boundaries.</dd></div><div><dt>Analysis artifacts</dt><dd>Chapter summaries, dossiers, emotions, tags, Smells, model attempts, and whole-book rollups.</dd></div><div><dt>Inferences</dt><dd>Book-level algorithms such as Connections and Questions &amp; Payoffs, built from saved evidence.</dd></div><div><dt>Human state</dt><dd>Dismissals and future reviewer decisions that must remain separate from regenerated machine output.</dd></div></dl>`],
      pipeline: ["Analysis pipeline", `<section class="information-lede compact"><p>Repeatable work</p><h2>Per-chapter evidence first; book-level synthesis second.</h2><p>The analysis pipeline records independent artifacts instead of producing one enormous, disposable answer.</p></section><ol class="pipeline-doc"><li><strong>Map the source</strong><span>Extract pages and establish chapter boundaries.</span></li><li><strong>Read the chapters</strong><span>Create summaries, dossiers, and chapter-scale signals with inspectable run details.</span></li><li><strong>Reconcile the book</strong><span>Combine current child artifacts into whole-book summaries and dossiers.</span></li><li><strong>Run inferences</strong><span>Apply slower cross-book algorithms to saved evidence.</span></li><li><strong>Render reports</strong><span>Present results without rerunning the analysis that created them.</span></li></ol><p>Failures belong to the affected artifact. They should remain inspectable and retryable without turning every other completed result back into unknown work.</p>`],
      models: ["Models", `<section class="information-lede compact"><p>Ollama model roles</p><h2>Different reading jobs have different costs.</h2><p>The Machine page is the source of truth for installed models, prerequisites, assignments, and readiness.</p></section><div class="model-doc"><article><h3>Deterministic tools first</h3><p>Extraction, chapter mapping, and local detectors avoid model work where a repeatable tool is the better instrument.</p></article><article><h3>Language models for interpretation</h3><p>Summaries, dossiers, reconciliation, and inference use a configured local model when the job requires semantic judgment.</p></article><article><h3>Time is observable</h3><p>Bookinator records model identity, input size, timing, attempts, and failures because local throughput varies dramatically by model and hardware.</p></article></div>`],
      privacy: ["Data and privacy", `<section class="information-lede compact"><p>The boundary</p><h2>Normal analysis remains on this computer.</h2><p>Book records, manuscripts, prompts, model output, and queue state are stored locally and excluded from Git.</p></section><ul class="privacy-doc"><li><strong>Loopback only:</strong> the Bookinator UI and API listen locally rather than publishing a public web service.</li><li><strong>Local inference:</strong> manuscript analysis is sent to the editor’s own Ollama service.</li><li><strong>Explicit network use:</strong> installing dependencies or models can contact external registries; manuscript text is not part of those installation requests.</li><li><strong>Export discipline:</strong> reports disclose which analysis was available and avoid embedding the source manuscript unless a future tool explicitly says otherwise.</li></ul>`],
    },
  },
  legal: {
    kicker: "Bookinator information", title: "Legal and privacy", intro: "Short, readable promises now; formal release documents before distribution.",
    tabs: {
      privacy: ["Privacy", `<h2>Local means local.</h2><p>Bookinator is designed to keep manuscripts, derived text, model prompts, embeddings, findings, and reports on the user's computer.</p><p>Installing a model may contact Ollama's registry. Manuscript content is not part of that request.</p>`],
      license: ["License", `<h2>Business Source License 1.1</h2><p>Bookinator 0.1.0 is source-available. Personal, educational, research, and internal business production use is permitted; offering Bookinator as a commercial hosted or managed service, or selling it as part of a competing commercial product, requires a separate commercial license.</p><p>On September 24, 2030, this version converts to GPL-3.0-or-later. The repository <code>LICENSE</code> file contains the controlling terms.</p>`],
      terms: ["Terms", `<h2>Editorial aid, not editorial authority</h2><p>Bookinator produces evidence-linked hypotheses. It can be wrong, overly literal, or unaware of deliberate ambiguity. Authors and editors remain responsible for applying its findings.</p>`],
    },
  },
  releases: {
    kicker: "Bookinator releases",
    title: "Milestones, not machinery",
    intro: "A high-level record of what each release made possible, why it mattered, and what Bookinator was not yet pretending to be.",
    tabs: {
      milestones: ["Milestones", `<section class="release-history" aria-labelledby="release-030-title">
        <header class="release-history-intro">
          <p>Product history</p>
          <h2>A record of useful leaps</h2>
          <p>This is intentionally not a list of commits. Each entry describes the change an editor could actually feel.</p>
        </header>
        <article class="release-entry planned">
          <aside class="release-spine">
            <span>v0.3.0</span>
            <time>Next<br>milestone</time>
            <i aria-hidden="true"></i>
          </aside>
          <div class="release-entry-body">
            <header>
              <div><p>Independent pipeline</p><h2 id="release-030-title">The Engine Room</h2></div>
              <span class="release-state">Planned</span>
            </header>
            <p class="release-lede">Analysis becomes a durable background service: controlled by the web UI, but no longer dependent on the web server or an open browser for its lifetime.</p>
            <section class="release-accomplishments" aria-label="Planned milestone pieces">
              <article><span>01</span><div><h3>One independent worker owns computation</h3><p>Scheduling, model calls, retries, cancellation, crash recovery, and pipeline-state writes move behind a stable process boundary.</p></div></article>
              <article><span>02</span><div><h3>Controllers share one protocol</h3><p>The web UI, command line, and a later menu-bar companion inspect and control the same worker instead of recreating its logic.</p></div></article>
              <article><span>03</span><div><h3>Background work behaves like a guest</h3><p>Pause-after-current, conservative concurrency, resource profiles, and battery and thermal awareness make unattended work legible and courteous.</p></div></article>
              <article><span>04</span><div><h3>Bookinator proves it before Inator inherits it</h3><p>The reusable pipeline contract moves to Inator only after reconnects, restarts, priorities, and failures have survived real Bookinator use.</p></div></article>
            </section>
            <section class="release-meaning"><p>Why it is next</p><h3>Hours of useful work deserve an engine, not a browser tab.</h3><p>The local worker boundary also creates the honest foundation for future menu-bar, LAN, or remote compute experiments without promising them yet.</p></section>
          </div>
        </article>
        <article class="release-entry current">
          <aside class="release-spine">
            <span>v0.2.0</span>
            <time>Release<br>candidate</time>
            <i aria-hidden="true"></i>
          </aside>
          <div class="release-entry-body">
            <header>
              <div><p>Human judgment milestone</p><h2 id="release-020-title">Reviewer Tools</h2></div>
              <span class="release-state">In progress</span>
            </header>
            <p class="release-lede">Bookinator became an editorial workspace: machine evidence remains inspectable, while a human can annotate the manuscript, judge model proposals, sign off, and carry those decisions into polished reports.</p>
            <section class="release-accomplishments" aria-label="Current milestone accomplishments">
              <article><span>01</span><div><h3>The reviewer can work in the manuscript</h3><p>Passage-linked notes can be categorized, reprioritized, edited in place, revisited, archived, or permanently removed without losing reading position.</p></div></article>
              <article><span>02</span><div><h3>Qwen became an inspectable first reader</h3><p>Significant concerns, soft leads, counterarguments, rubric scores, exact source anchors, and whole-book synthesis remain distinct from human judgment.</p></div></article>
              <article><span>03</span><div><h3>Whole-book evidence became editorial reporting</h3><p>Summaries, emotions, tags, smells, chapter length, questions, reviewer notes, and LLM Review travel into Explore, HTML, and PDF.</p></div></article>
              <article><span>04</span><div><h3>Chapter maps became testable infrastructure</h3><p>A 350-specimen corpus catches EPUB and text disagreements, while genuinely ambiguous structures stop for review before expensive analysis.</p></div></article>
            </section>
            <section class="release-meaning"><p>Release gate</p><h3>Carmilla gets the complete treatment.</h3><p>Fresh EPUB ingestion through all analysis, human annotation, sign-off, backup and restore, interactive HTML, and rendered PDF—then inspection of the actual artifacts.</p></section>
          </div>
        </article>
        <article class="release-entry delivered">
          <aside class="release-spine">
            <span>v0.1.0</span>
            <time datetime="2026-09-24">Sep 24<br>2026</time>
            <i aria-hidden="true"></i>
          </aside>
          <div class="release-entry-body">
            <header>
              <div><p>First working milestone</p><h2 id="release-010-title">Holy Crap, that Worked</h2></div>
              <span class="release-state">Delivered</span>
            </header>
            <p class="release-lede">Bookinator became an end-to-end, local editorial workbench: bring in a manuscript, build a durable understanding chapter by chapter, explore patterns across the whole book, and share a professional report.</p>
            <section class="release-accomplishments" aria-label="Milestone accomplishments">
              <article><span>01</span><div><h3>A manuscript becomes a navigable book</h3><p>Import, chapter structure, preserved source, and analysis connected back to the passages that produced it.</p></div></article>
              <article><span>02</span><div><h3>The machine remembers beyond one prompt</h3><p>Chapter summaries and evidence-rich dossiers accumulate into whole-book understanding instead of isolated answers.</p></div></article>
              <article><span>03</span><div><h3>Editors can see the shape of the story</h3><p>Emotion maps, editorial tags, and prose smells reveal patterns that are difficult to notice while reading linearly.</p></div></article>
              <article><span>04</span><div><h3>Distant details become connected</h3><p>Book-wide indexes, connections, and questions with payoffs turn scattered observations into things an editor can follow.</p></div></article>
              <article><span>05</span><div><h3>Analysis can be trusted carefully</h3><p>Pipeline state, model runs, failures, evidence, and source passages stay inspectable. The app offers arguments, not oracles.</p></div></article>
              <article><span>06</span><div><h3>The work can leave the app</h3><p>A branded, book-specific PDF turns the strongest available analysis into a professional artifact for another reader.</p></div></article>
            </section>
            <section class="release-meaning"><p>Why it mattered</p><h3>The pieces stopped feeling like experiments and began behaving like one product.</h3><p>This milestone proved the full loop on a real book while keeping manuscripts and model work local to the editor’s computer.</p></section>
            <section class="release-boundary"><strong>What came next</strong><p>Reviewer annotations, machine-assisted first reading, stronger reports, chapter-map hardening, and a human sign-off workflow became the center of Reviewer Tools.</p></section>
          </div>
        </article>
      </section>`],
    },
  },
  roadmap: {
    kicker: "Bookinator roadmap",
    title: "A larger memory for the book",
    intro: "This is the working field of possibilities: practical editorial wins, enabling foundations, and ambitious experiments. The order is a hypothesis, not a promise—sort it to see what rises when ease, impact, or subject matters most.",
    tabs: {
      priorities: ["Priorities", `<section class="roadmap-introduction"><div><h2>Build the editorial loop, then widen the intelligence.</h2><p>Bookinator already reads a manuscript as connected evidence rather than isolated prompts. The next work closes the loop between machine observation, human judgment, author revision, and trustworthy sharing. Beyond that lie deeper models of causality, reader memory, character state, geography, and time.</p></div><dl><div><dt>Ease</dt><dd>How directly the idea can grow from foundations already in Bookinator.</dd></div><div><dt>Impact</dt><dd>How much editorial or author value the finished capability could create.</dd></div><div><dt>Payoff</dt><dd>Ease × impact. A useful first ordering—not a substitute for judgment.</dd></div></dl></section><section class="roadmap-landscape" aria-label="Roadmap payoff landscape"><div><strong>Close the loop</strong><span>Reviewer · Author editing · Revisions · Sharing</span></div><i aria-hidden="true"></i><div><strong>Understand the book</strong><span>Scenes · Characters · Causality · Reader memory</span></div><i aria-hidden="true"></i><div><strong>Explore the frontier</strong><span>Chronology · Maps · Simulations · Time travel</span></div></section><section class="roadmap-ledger" data-roadmap-ledger></section>`],
    },
  },
};
